sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run ci
deploy:
  provider: heroku
    api_key:
      secure: "f04e2d74-d805-4b0c-b731-babcde0ea813"
  app:
    develop: platform-for-testing-front